### PR TITLE
Fixes #2726. Update expected errors positions

### LINKED ISSUE #2726: co19/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04
```console
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 08.000700s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=macros --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04.dart

static error failures:
- Missing expected unspecified error at tests/co19/src/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04_lib.dart line 21, column 24, length 1.

- Unexpected error at tests/co19/src/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04.dart line 27, column 16, length 1: COMPILE_TIME_ERROR.CONFLICTING_GENERIC_INTERFACES

- Unexpected error at tests/co19/src/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04.dart line 27, column 16, length 1: COMPILE_TIME_ERROR.INCONSISTENT_INHERITANCE

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04
```

In the analyzer we report this error not a specific type annotation, bot in the name of the declaration where it becomes an error. Both type annotations are fine, it is an error to merge them. We do the same regardless if it is augmentations or not.

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t07_lib.dart [hunk 1]
```diff
@@ -22,6 +22,6 @@ augment library 'augmenting_types_A06_t07.dart';
 augment class C1 extends A {}
 
 augment abstract class C2 extends A {}
-//                                ^
+
+// [error line 28, column 47]
```
Comment (eernstg) [inline LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t07_lib.dart:26]: Is it really true that the error is reported at a location which is beyond the end of the file? If it is actually the observed behavior then it sounds like that would be a thing to fix in the tool, rather than a thing to expect and preserve for an unknown amount of time...

**Review by eernstg — COMMENTED** [review]
Looks good, but one error expectation location seems wrong, so PTAL.

File: LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t07_lib.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t07_lib.dart]: Thank you! Seems that this error is obsolete. Line 28 was the last empty line of the file, but this is not relevant any longer

**Comment by sgrekhov** [comment]
Removed. The tests passes on the latest SDK. PTAL

**Review by eernstg — APPROVED** [review]
LGTM
