### PR TITLE
Fixes #3542. Fix secondary errors in `static_processing_A22_t01.dart`

### LINKED ISSUE #3542: co19/LanguageFeatures/Primary-constructors/static_processing_A22_t01
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A22_t01
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 04.000557s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/fshcheglov/Source/Dart/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=primary-constructors --ignore-unrecognized-flags --packages=/Users/fshcheglov/Source/Dart/sdk/.dart_tool/package_config.json --format=json /Users/fshcheglov/Source/Dart/sdk/tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t01.dart

static error failures:
- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t01.dart line 41, column 7, length 1: COMPILE_TIME_ERROR.NOT_INITIALIZED_NON_NULLABLE_INSTANCE_FIELD

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t01.dart line 70, column 6, length 1: COMPILE_TIME_ERROR.FINAL_NOT_INITIALIZED_CONSTRUCTOR

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A22_t01
```

The error is in this block of code:
```
class C<T>(var String v1, final T v2, var bool v3) {
  String get v1 => "";
//           ^^
// [analyzer] unspecified
// [cfe] unspecified
  T v2;
//  ^^
// [analyzer] unspecified
// [cfe] unspecified
  void v3() {}
//     ^^
// [analyzer] unspecified
// [cfe] unspecified
}
```

In class `C`, `T v2;` causes an error to be reported due to being uninitialized, while not being nullable. While this is an unideal scenario, it is neither a bug with the analyzer nor with co19. It is recommended to change its type to `T? v2` to resolve the issue, as this error is not what the file is intended to test. A similar problem occurs in `E` with `final T v1;`

### PR DESCRIPTION
**Pull request by sgrekhov**
The test fails because secondary errors are being reported. This change fixes them.

### CODE REVIEW

File: LanguageFeatures/Primary-constructors/static_processing_A22_t01.dart [hunk 1]
```diff
@@ -67,11 +67,11 @@ extension type ET2(String v) {
 // [cfe] unspecified
 }
 
-enum E<T>(final T v1, final String v2, final bool v3) {
+enum E<T>(final T? v1, final String v2, final bool v3) {
   e0<int>(1, "E1", true);
 
-  final T v1;
-//        ^^
+  final T? v1;
```
Comment (eernstg) [inline LanguageFeatures/Primary-constructors/static_processing_A22_t01.dart]: I think this will work:

```suggestion
  final T? v1 = null;
```

**Review by eernstg — COMMENTED** [review]
One more adjustment again.
