### PR TITLE
Fixes #1851. Roll failures fixed

### LINKED ISSUE #1851: Failures on [co19] Roll co19 to 155e546ce33f3d4532375bfaaa21b7322e81e833
There are new test failures on [[co19] Roll co19 to 155e546ce33f3d4532375bfaaa21b7322e81e833](https://dart-review.googlesource.com/c/sdk/+/282441).

The tests
```
co19/LanguageFeatures/Patterns/object_A07_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/object_A07_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A01_t01 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A01_t04 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A02_t01 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A03_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A04_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A06_t02 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A06_t03 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A07_t01 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A07_t02 Crash (expected Pass)
co19/LanguageFeatures/Patterns/pattern_context_A07_t03 Crash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t04 Crash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t04 DartkCrash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t05 Crash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t06 Crash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t06 DartkCrash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t09 DartkCrash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t09 Crash (expected Pass)
co19/LanguageFeatures/Patterns/scope_A02_t10 Crash (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A01_t01 Crash (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A01_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A01_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A02_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A02_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A02_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A04_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Patterns/shared_case_scope_A04_t01 Crash (expected Pass)
co19/LanguageFeatures/Patterns/type_inference_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Patterns/type_inference_A02_t01 CompileTimeError (expected Pass)
    and 17 more tests
```
are failing on configurations
```
analyzer-asserts-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-chrome
dart2wasm-hostasserts-linux-x64-d8
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart [hunk 1]
```diff
@@ -79,6 +81,8 @@ main() {
       print(a);
       break;
     case int a when a == 42:
+//           ^
+// [cfe] unspecified
```
Comment (eernstg) [inline LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:85]: I do not understand this error: The log seems to imply that it's a 'Variable pattern 'a' doesn't have the same type in all cases' problem, but I think they should both (line 80 `a` and line 82 `a`) have declared type `int`.

**Review by eernstg — COMMENTED** [review]
Just wondering why there would be an error in line 83 of LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart, wouldn't that be an issue with the CFE (command "fasta")?

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:85]: It's how CFE behaves now. It reports an additional error here. If you believe that it sholdn't I can revert change in this file. Please confirm

Comment (eernstg) [reply LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:85]: Oh, wait, I misread the situation: We have shared-body cases in lines 83, 86, 87 (types `int`, `String`, `int`), so I'd expect an error at line 88 when `a` is used in the body.

But I still don't understand why there would be an error at line 83. It is _not_ an error for multiple cases with a shared body to declare a variable with the same name `a` and different types/finality, as long as it isn't used in the body. If it is used then there will be an error _at the usage_, not in one or more cases.

Comment (eernstg) [reply LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:85]: I think we should maintain that there is no error in line 83.

**Review by eernstg — COMMENTED** [review]
Responded in the thread about the surprising error on line 83.

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart [hunk 2]
```diff
@@ -62,6 +62,8 @@ main() {
       print(a);
       break;
     case final int a when a == 42:
+//                 ^
+// [cfe] unspecified
```
Comment (eernstg) [inline LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:66]: I thought we should have this error message, but at this point I do not think we should have it: There is no error just because we have different declarations of `a` with different types/finalities, it's only an error to _use_ that variable in the body.

So there's no error here, either.

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart [hunk 3]
```diff
@@ -96,6 +100,8 @@ main() {
...
```
Comment (eernstg) [inline LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:104]: Same here: no error.

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart [hunk 4]
```diff
@@ -96,6 +100,8 @@ main() {
...
     case final a:
       print(a);
 //          ^
```
Comment (eernstg) [inline LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart:107]: This error is fine!

**Review by eernstg — COMMENTED** [review]
Added a couple of extra comments: I misread the situation, and there are more spurious errors than I thought at first.

File: LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart]: Reverted changes in shared_case_scope_A01_t02.dart

Comment (eernstg) [reply LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart]: Thx!

**Review by eernstg — APPROVED** [review]
LGTM.
