### PR TITLE
Fixes #2859. Hide public extension methods if an import is deferred

### LINKED ISSUE #2859: co19/LanguageFeatures/Parts-with-imports/scope_A03_t03
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Parts-with-imports/scope_A03_t03
Expected: Pass
Actual: CompileTimeError

--- Command "dart2analyzer" (took 38ms):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=enhanced-parts --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Parts-with-imports/scope_A03_t03.dart

unexpected analysis errors in scope_A03_t03_part1.dart:
- Line 22, column 8: COMPILE_TIME_ERROR.DEFERRED_IMPORT_OF_EXTENSION
  Imports of deferred libraries must hide all extensions.

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Parts-with-imports/scope_A03_t03
```

### PR DESCRIPTION
**Pull request by sgrekhov**
The updated test works in the latest SDK. @eernstg is it expected that extension types can be loaded defferedly?

### CODE REVIEW

**Comment by eernstg** [comment]
Yes, an extension type can certainly be obtained as the result of importing a library, and it shouldn't make any difference that the import is deferred (except for the usual stuff like the need to call `loadLibrary()` etc.).

File: LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart [hunk 1]
```diff
@@ -19,7 +19,7 @@
 
 part of 'scope_A03_t03.dart';
 
-import 'scope_lib1.dart' deferred as d;
+import 'scope_lib1.dart' deferred as d hide LibExt;
```
Comment (eernstg) [inline LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: Just wondering, why would `LibExt` be subject to a `hide` here?

**Review by eernstg — COMMENTED** [review]
Looks benign, but I'm just curious why the `hide` was introduced.

File: LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: Otherwise `deferred_import_of_extension` error occurs. Hiding of this extension eleminates the error.

Comment (eernstg) [reply LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: Oh! (checking specs...)

Comment (eernstg) [reply LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: OK. "This is a temporary restriction ensuring that no extensions are introduced using deferred imports, allowing us to later introduce semantics for such extensions without affecting existing code". It was too scary. :grinning:

Comment (eernstg) [reply LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: We have no such rule for extension types.

Comment (eernstg) [reply LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart:22]: (And I'm not sure why an extension or an extension type should be more scary than a top-level function. After all, that's how they are compiled anyway.)

**Comment by eernstg** [comment]
But this means that the `hide` is needed because `LibExt` is an extension. Thanks!

**Review by eernstg — APPROVED** [review]
LGTM
