### PR TITLE
Fixes #1699. variable_A01_t01.dart. Fix types used in a list pattern

### LINKED ISSUE #1699: co19/LanguageFeatures/Patterns/variable_A01_t01
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Patterns/variable_A01_t01
Expected: Pass
Actual: CompileTimeError

--- Command "dart2analyzer" (took 06.000360s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=patterns,records --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Patterns/variable_A01_t01.dart

unexpected analysis errors in variable_A01_t01.dart:
- Line 52, column 26: COMPILE_TIME_ERROR.LIST_ELEMENT_TYPE_NOT_ASSIGNABLE
  The element type 'double' can't be assigned to the list type 'int'.

- Line 56, column 23: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'double Function(double)' doesn't conform to the bound 'int Function(int)' of the type parameter 'R'.

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Patterns/variable_A01_t01
```

Code
```dart
  var [int a2, b2] = [1, 3.14];
```
Here `b2` does not specify the type, so does not participate in computing the required type of `[int a2, b2]`. The resulting required type is `List<int>` as if we wrote `<int>[a2, b2]`. So, the context type of `[1, 3.14]` is also `List<int>`, and `3.14` is not valid there.

image

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Patterns/variable_A01_t01.dart [hunk 1]
```diff
@@ -49,11 +49,11 @@ main() {
...
   Expect.equals("6", d1);
 
-  var [int a2, b2] = [1, 3.14];
+  var [int a2, b2] = [1, 2 as num];
   Expect.equals(1, a2);
-  Expect.equals(3.14, b2);
+  Expect.equals(2, b2);
   a2.expectStaticType<Exactly<int>>();
-  b2.expectStaticType<Exactly<double>>();
+  b2.expectStaticType<Exactly<int>>();
```
Comment (eernstg) [inline LanguageFeatures/Patterns/variable_A01_t01.dart:56]: Have to ask: Why isn't `[1, 2 as num]` inferred as a `<num>[...]` list literal and subsequently `[int a2, b2]` inferred as a `<num>[...]` list pattern, and `int a2` is then a compile-time error because it's a variable pattern with a built-in downcast in a declaration context?

**Review by eernstg — COMMENTED** [review]
A question came up

File: LanguageFeatures/Patterns/variable_A01_t01.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Patterns/variable_A01_t01.dart:56]: Indeed. Thank you! Fixed. Please rereview

Comment (eernstg) [reply LanguageFeatures/Patterns/variable_A01_t01.dart:56]: Thx!

**Review by eernstg — APPROVED** [review]
LGTM
