### PR TITLE
Fixes #2574. Expect an error in case of augmenting a type alias

### LINKED ISSUE #2574: [augmentation-libraries] Cover success case for aliased augmenting declarations
PR https://github.com/dart-lang/co19/pull/2568 contains a test LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t02.dart checking that we get the expected compile-time errors in the case where a type alias of a type declaration of a mismatched kind is augmented.

Do we have a test which is testing the same situation, except that the type aliases denote types of the same kind? (That is, the case where we should not get an error because there is no kind mismatch, but there might still be an error because a tool mistakenly treats the type alias as a new and different kind and fails to see that the type alias denotes a declaration of the right kind).

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

**Comment by sgrekhov** [comment]
Thank you for the detailed explanation. Tests updated and hopefully now it's clearer what exactly is tested. Please take another look

File: LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t03.dart [hunk 1]
```diff
@@ -26,12 +25,8 @@ typedef CAlias = C;
 typedef MAlias = M;
 typedef EAlias = E;
```
Comment (eernstg) [inline LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t03.dart:26]: Is it true that these three declarations could just be removed? I don't see them in use anywhere.

**Review by eernstg — COMMENTED** [review]
Looks good!

Just one thing: If I'm right that three declarations in LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t03.dart are never used then they might as well be removed.

File: LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t03.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t03.dart]: Right. Thank you! Removed

**Review by eernstg — APPROVED** [review]
LGTM
