### PR TITLE
Fixes #3516. Update expected errors in static_processing_A24_t05.dart

### LINKED ISSUE #3516: co19/LanguageFeatures/Primary-constructors/static_processing_A24_t05
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A24_t05
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 04.000229s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/fshcheglov/Source/Dart/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=primary-constructors --ignore-unrecognized-flags --packages=/Users/fshcheglov/Source/Dart/sdk/.dart_tool/package_config.json --format=json /Users/fshcheglov/Source/Dart/sdk/tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart

static error failures:
- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 26, column 3, length 5: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 34, column 3, length 5: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 50, column 3, length 7: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 58, column 3, length 5: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 67, column 3, length 5: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 76, column 3, length 8: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart line 85, column 3, length 8: COMPILE_TIME_ERROR.CONST_EVAL_THROWS_EXCEPTION

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A24_t05
```

Primary constructor body attempts to write to `x` twice, which reports a compile-time exception at the point where the constructor is used. Tests should expect this exception as well. This is due to an unfortunate feature of the analyzer which causes it to report two compile-time errors instead of one in this case.

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart [hunk 1]
```diff
@@ -32,22 +34,26 @@ enum E1(final int x) {
...
+// [analyzer] unspecified
   this: x = 2;
 //      ^
 // [analyzer] unspecified
 // [cfe] unspecified
 }
 
 enum E3({int x = 0}) {
-  e(x: 0);
+  e0(x: 0);
```
Comment (sgrekhov) [inline LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart]: Why there is no error here, on line 46? 

cc @fshcheglov

Comment (eernstg) [reply LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart]: Parameter `x` is not declaring, so there is no `x` instance variable, and the enumerated value declaration `e0(x: 0)` does not doubly initialize anything.

Comment (eernstg) [reply LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart]: Perhaps this test case just goes away, because the parameter can't be `{var int x = 0}`.

Comment (sgrekhov) [reply LanguageFeatures/Primary-constructors/static_processing_A24_t05.dart]: Thanks! Tthe test check an instance variable, so there is definitely missing `final` keyword. Fixed. PTAL.

**Review by eernstg — APPROVED** [review]
LGTM
