### PR TITLE
Fixes #3730. Update expected errors in `definition_t16.dart`

### LINKED ISSUE #3730: Failing tests for primary constructors flag flip (3.13)
While prepping a flag flip CL, I noticed that these co19 tests are failing.
I looked at some of them and they seem to be failing from using `var`/`final` keywords. I didn't go through all of them, but I suspect that should be most, if not all, the errors.

Could we update these tests so that they can pass when primary constructors is enabled for the upcoming 3.13 release?
Here is the flag flip CL if you'd like to look at the logs of each test: https://dart-review.googlesource.com/c/sdk/+/489241

cc. @sgrekhov @eernstg 

```
co19/Language/Classes/Constructors/Factories/name_t01
co19/Language/Classes/Constructors/Factories/name_t03
co19/Language/Classes/Constructors/Factories/name_t04
co19/Language/Classes/Constructors/Factories/name_t05
co19/Language/Classes/Constructors/Factories/name_t06
co19/Language/Classes/Constructors/Factories/name_t07
co19/Language/Classes/Instance_Methods/override_named_parameters_t02
co19/Language/Classes/Instance_Methods/override_named_parameters_t08
co19/Language/Expressions/Assignable_Expressions/subscript_expression_super_t01
co19/Language/Expressions/Assignable_Expressions/subscript_expression_t01
co19/Language/Expressions/Bitwise_Expressions/method_invocation_t01
co19/Language/Expressions/Bitwise_Expressions/method_invocation_t02
co19/Language/Expressions/Bitwise_Expressions/method_invocation_t03
co19/Language/Expressions/Bitwise_Expressions/syntax_t01
co19/Language/Expressions/Bitwise_Expressions/syntax_t02
co19/Language/Expressions/Instance_Creation/New/evaluation_t09
co19/Language/Expressions/Multiplicative_Expressions/syntax_t07
co19/Language/Expressions/Multiplicative_Expressions/syntax_t08
co19/Language/Expressions/Multiplicative_Expressions/syntax_t09
co19/Language/Expressions/Shift/equivalent_super_t01
co19/Language/Expressions/Shift/equivalent_super_t02
co19/Language/Expressions/Shift/equivalent_t01
co19/Language/Expressions/Shift/equivalent_t02
co19/Language/Functions/External_Functions/not_connected_to_a_body_t01
co19/Language/Functions/External_Functions/not_connected_to_a_body_t02
co19/Language/Functions/External_Functions/not_connected_to_a_body_t03
co19/Language/Functions/External_Functions/not_connected_to_a_body_t06
co19/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t06
co19/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t10
co19/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t16
co19/Language/Functions/Formal_Parameters/syntax_t05
co19/Language/Functions/Formal_Parameters/syntax_t12
co19/Language/Generics/typedef_A01_t03
co19/Language/Statements/Expression_Statements/syntax_t06
co19/Language/Types/Function_Types/subtype_named_args_t01
co19/Language/Types/Function_Types/subtype_optional_args_t01
co19/Language/Types/Function_Types/subtype_optional_args_t11
co19/Language/Types/Function_Types/subtype_optional_args_t12
co19/Language/Types/Interface_Types/subtype_t07
co19/Language/Variables/syntax_t16
co19/LanguageFeatures/Enhanced-Enum/grammar_A05_t01
co19/LanguageFeatures/Enhanced-Enum/grammar_A05_t02
co19/LanguageFeatures/Extension-methods/syntax_t07
co19/LanguageFeatures/Extension-types/syntax_A05_t02
co19/LanguageFeatures/Spread-collections/DynamicSemantics_List_A02_t02
co19/LanguageFeatures/Spread-collections/DynamicSemantics_List_A02_t03
co19/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t02
co19/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t03
co19/LanguageFeatures/Spread-collections/DynamicSemantics_Set_A02_t02
co19/LanguageFeatures/Spread-collections/DynamicSemantics_Set_A02_t03
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t01
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t02
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t03
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t04
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t05
co19/LanguageFeatures/Spread-collections/TypeInference_A01_t06
co19/LanguageFeatures/Wildcards/binding_A02_t03
co19/LanguageFeatures/nnbd/syntax_A05_t01
co19/LanguageFeatures/nnbd/syntax_A05_t02
co19/LanguageFeatures/nnbd/syntax_A05_t03
co19/LibTest/collection/LinkedHashSet/iterator_A01_t02
```

### PR DESCRIPTION
**Pull request by sgrekhov**
The updated test passes in the analyzer and CFE.

### CODE REVIEW

File: Language/Classes/definition_t16.dart [hunk 1]
```diff
@@ -12,14 +12,14 @@
 /// Class body is not empty.
 /// @author rodionov
 
+// SharedOptions=--enable-experiment=primary-constructors
```
Comment (eernstg) [inline Language/Classes/definition_t16.dart:15]: It isn't obvious which behaviors we'd consider to be correct when there is a syntax error, so we'd just have to accept that the tools report errors as shown below.

However, I don't quite understand why it helps to enable primary constructors (yes, they allow for the `(` right after the class name, so we should definitely have a test where primary constructors are enabled and we still confirm that the error is detected).

I just don't understand why the test isn't valid in a situation where primary constructors do not exist.

**Review by eernstg — APPROVED** [review]
LGTM.

I'll land this PR now.

However, I asked a question in the review, it would be great if you could comment on it.

File: Language/Classes/definition_t16.dart (hunk 1 above)
Comment (eernstg) [reply Language/Classes/definition_t16.dart:15]: Thinking about this one more time: It is actually not very important to preserve the testing for older versions (where primary constructors do not exist), because we _are_ going to have primary constructors. So it's not a problem to say that this test relies on primary constructors and we don't care what happens when they are disabled.

Comment (sgrekhov) [reply Language/Classes/definition_t16.dart:15]: Without primary constructors, the analyzer produces an error on ( after the class name, and it doesn't produce this error when the feature is disabled. Therefore, we have two sets of errors: with the feature enabled and without it. So I enabled the feature and expect the behavior produced by the tools.

Comment (eernstg) [reply Language/Classes/definition_t16.dart:15]: Makes sense, thanks!
