### PR TITLE
Fixes #2838. Variable named `_` does not bind anything

### LINKED ISSUE #2838: [Wildcard Variables] Update tests or test expectations using wildcards unintentionally.
These tests need updating at some point because they start failing as we're [prepping for the wildcard variable experiment flag flip](https://dart-review.googlesource.com/c/sdk/+/381311):

- co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t01
- co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t02
- co19/Language/Expressions/Identifier_Reference/syntax_t01
- co19/Language/Expressions/Strings/String_Interpolation/no_quote_t01
- co19/Language/Overview/Privacy/private_and_public_t14
- co19/Language/Overview/Privacy/private_and_public_t15
- co19/LanguageFeatures/Patterns/pattern_context_A06_t03

Unless these test for specific wildcard behaviour, we should avoid using `_`.

cc. @eernstg @sgrekhov 

Test failures: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8738410861472445857/+/u/test_results/new_test_failures__logs_

<details> 
  <summary>Uncollapse this for inlined test failure results.</summary>

```
/===========================================================================================================\
| co19/Language/Expressions/Identifier_Reference/syntax_t01 broke (Pass -> CompileTimeError, expected Pass) |
\===========================================================================================================/

--- Command "fasta" (took 16ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Expressions_Identifier_Reference_syntax_t01/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Expressions/Identifier_Reference/syntax_t01.dart )

exit code:
1

stdout:
tests/co19/src/Language/Expressions/Identifier_Reference/syntax_t01.dart:49:3: Error: Undefined name '_'.
  _;
  ^

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Expressions/Identifier_Reference/syntax_t01


/=====================================================================================================================\
| co19/Language/Expressions/Strings/String_Interpolation/no_quote_t01 broke (Pass -> CompileTimeError, expected Pass) |
\=====================================================================================================================/

--- Command "fasta" (took 17ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Expressions_Strings_String_Interpolation_no_quote_t01/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Expressions/Strings/String_Interpolation/no_quote_t01.dart )

exit code:
1

stdout:
tests/co19/src/Language/Expressions/Strings/String_Interpolation/no_quote_t01.dart:22:26: Error: Undefined name '_'.
  Expect.stringEquals("${_}", "$_");
                         ^
tests/co19/src/Language/Expressions/Strings/String_Interpolation/no_quote_t01.dart:22:33: Error: Undefined name '_'.
  Expect.stringEquals("${_}", "$_");
                                ^

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Expressions/Strings/String_Interpolation/no_quote_t01


/============================================================================================================================\
| co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t01 broke (Pass -> MissingCompileTimeError, expected Pass) |
\============================================================================================================================/

--- Command "fasta" (took 13ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Functions_Formal_Parameters_Optional_Formals_name_t01/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Functions/Formal_Parameters/Optional_Formals/name_t01.dart )

static error failures:
- Unexpected error at tests/co19/src/Language/Functions/Formal_Parameters/Optional_Formals/name_t01.dart line 23, column 6: No named parameter with the name '_'.

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t01


/============================================================================================================================\
| co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t02 broke (Pass -> MissingCompileTimeError, expected Pass) |
\============================================================================================================================/

--- Command "fasta" (took 15ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Functions_Formal_Parameters_Optional_Formals_name_t02/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart )

static error failures:
- Unexpected error at tests/co19/src/Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart line 32, column 9: No named parameter with the name '_'.

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Functions/Formal_Parameters/Optional_Formals/name_t02


/=======================================================================================================\
| co19/Language/Overview/Privacy/private_and_public_t14 broke (Pass -> CompileTimeError, expected Pass) |
\=======================================================================================================/

--- Command "fasta" (took 17ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Overview_Privacy_private_and_public_t14/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart )

exit code:
1

stdout:
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:20:27: Error: The getter '_' isn't defined for the class 'A'.
 - 'A' is from 'tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '_'.
  fun(_, _$, ___) {return _ + _$ + ___;}
                          ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:21:39: Error: Undefined name '_'.
  static staticfun(_, _$, __) {return _ + _$ + __;}
                                      ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:25:32: Error: Undefined name '_'.
  A(_, _$, this.__) : _check = _ + _$ {}
                               ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:26:34: Error: Undefined name '_'.
  A.named(_, _$, ___) : _check = _ + _$ + ___ {}
                                 ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:28:29: Error: The getter '_' isn't defined for the class 'A'.
 - 'A' is from 'tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '_'.
  void set _setter(_) {__ = _;}
                            ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:33:15: Error: Undefined name '_'.
  return _x + _;
              ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t14.dart:46:28: Error: Undefined name '_'.
  Expect.equals(1, ((_) => _)(1));
                           ^

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Overview/Privacy/private_and_public_t14


/=======================================================================================================\
| co19/Language/Overview/Privacy/private_and_public_t15 broke (Pass -> CompileTimeError, expected Pass) |
\=======================================================================================================/

--- Command "fasta" (took 14ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_Language_Overview_Privacy_private_and_public_t15/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart )

exit code:
1

stdout:
tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart:19:3: Error: Type '_' not found.
  _? x = null;
  ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart:25:23: Error: Type '_' not found.
class G3<_> extends G<_, _, _>{}
                      ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart:25:26: Error: Type '_' not found.
class G3<_> extends G<_, _, _>{}
                         ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart:25:29: Error: Type '_' not found.
class G3<_> extends G<_, _, _>{}
                            ^
tests/co19/src/Language/Overview/Privacy/private_and_public_t15.dart:19:3: Error: '_' isn't a type.
  _? x = null;
  ^

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/Language/Overview/Privacy/private_and_public_t15


/========================================================================================================\
| co19/LanguageFeatures/Patterns/pattern_context_A06_t03 broke (Pass -> CompileTimeError, expected Pass) |
\========================================================================================================/

--- Command "fasta" (took 88ms):
(cd /b/s/w/ir/cache/builder/sdk/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_LanguageFeatures_Patterns_pattern_context_A06_t03/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --packages=./.dart_tool/package_config.json ./tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart )

exit code:
1

stdout:
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:22:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:25:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:28:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:31:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:34:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^
tests/co19/src/LanguageFeatures/Patterns/pattern_context_A06_t03.dart:37:20: Error: Undefined name '_'.
  Expect.equals(0, _);
                   ^

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/LanguageFeatures/Patterns/pattern_context_A06_t03
```
</details>

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart [hunk 1]
```diff
@@ -30,4 +30,7 @@ class C {
 main() {
   new A(_p: "Optional parameter names must not begin with an underscore!");
```
Comment (eernstg) [inline Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart:31]: Wouldn't this one be an error as well?

File: LanguageFeatures/Wildcards/binding_A01_t13.dart [hunk 2]
```diff
@@ -0,0 +1,26 @@
+// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
+// for details. All rights reserved. Use of this source code is governed by a
+// BSD-style license that can be found in the LICENSE file.
+
+/// @assertion A local declaration whose name is `_` does not bind that name to
+/// anything.
+///
+/// @description Checks that it is a compile-time error to use a variable named
+/// `_` in a string literal.
```
Comment (eernstg) [inline LanguageFeatures/Wildcards/binding_A01_t13.dart:9]: Perhaps?:
```suggestion
/// @description Checks that an identifier reference of the form `_` in a string literal does
/// not resolve to a local variable which is a wildcard since there is no such binding.
```

**Review by eernstg — COMMENTED** [review]
Looks good! It does look like we should expect one more error, or did I miss something?

File: Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart (hunk 1 above)
Comment (sgrekhov) [reply Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart:31]: No. Declaration of named parameters with the names `_` and `_p` is an error. But invocation of the function with these parameters seems a secondary error and reported for `_` only.

File: LanguageFeatures/Wildcards/binding_A01_t13.dart (hunk 2 above)
Comment (sgrekhov) [reply LanguageFeatures/Wildcards/binding_A01_t13.dart]: Updated

File: Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart (hunk 1 above)
Comment (eernstg) [reply Language/Functions/Formal_Parameters/Optional_Formals/name_t02.dart:31]: Good catch!

I created https://github.com/dart-lang/language/issues/4062 in response to this behavior, I think we might as well make it an error.

But then we'll keep this as it is, and make changes if 4062 creates a need for that.

**Review by eernstg — APPROVED** [review]
LGTM
