### PR TITLE
Fixes #3039. Fix the new roll failures

### LINKED ISSUE #3039: Failures on [co19] Roll co19 to 044cf88601e2ac6054c1fe39706be837c1471278
There are new test failures on [[co19] Roll co19 to 044cf88601e2ac6054c1fe39706be837c1471278](https://dart-review.googlesource.com/c/sdk/+/403862).

The tests
```
co19/Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t02 MissingCompileTimeError (expected Pass)
co19/Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t04 MissingCompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Application/implicit_constructor_A01_t05 CompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Application/implicit_constructor_A02_t03 CompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Application/implicit_constructor_A03_t06 CompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Application/implicit_constructor_A03_t07 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A02_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A08_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A08_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t04 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t06 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t08 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t10 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t12 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t14 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t16 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/constant_expression_A10_t18 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/equality_A01_t09 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/equality_A02_t06 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t04 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t05 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t06 CompileTimeError (expected Pass)
co19/LanguageFeatures/Static-access-shorthand/grammar_A04_t07 CompileTimeError (expected Pass)
    and 9 more tests
```
are failing on configurations
```
analyzer-asserts-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-linux-chrome-unsound
dart2js-hostasserts-linux-d8
dart2js-linux-chrome
dart2wasm-asserts-linux-chrome
dart2wasm-linux-chrome
dart2wasm-linux-d8
dart2wasm-linux-jscm-chrome
ddc-linux-chrome
vm-aot-linux-release-x64
vm-mac-debug-arm64
vm-win-release-x64
```

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03.dart [hunk 1]
```diff
@@ -29,10 +29,11 @@ class C {
 
 extension type const ET(String value) {
   const ET.id(this.value, [String s = ""]);
-  const factory ET.f(String value, {String s = ""}) = ET;
+  const ET.id2(this.value, {String s = ""});
+  const factory ET.f(String value, {String s}) = ET.id2;
 }
 
-main() {
+main() {/*
```
Comment (eernstg) [inline LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03.dart:36]: Is the line range 36-97 intended to be commented out? Looks like a temporary modification that wasn't undone.

**Review by eernstg — COMMENTED** [review]
Just one question: Is that long comment intended?

File: LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03.dart]: Of course. Thank you. Fixed.

Comment (eernstg) [reply LanguageFeatures/Static-access-shorthand/constant_expression_A01_t03.dart]: Thanks!

**Review by eernstg — APPROVED** [review]
LGTM
