### PR TITLE
Fixes #3543. Fix secondary errors in `static_processing_A22_t02.dart`

### LINKED ISSUE #3543: co19/LanguageFeatures/Primary-constructors/static_processing_A22_t02
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A22_t02
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 04.000293s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/fshcheglov/Source/Dart/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=primary-constructors --ignore-unrecognized-flags --packages=/Users/fshcheglov/Source/Dart/sdk/.dart_tool/package_config.json --format=json /Users/fshcheglov/Source/Dart/sdk/tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t02.dart

static error failures:
- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t02.dart line 41, column 7, length 1: COMPILE_TIME_ERROR.NOT_INITIALIZED_NON_NULLABLE_INSTANCE_FIELD

- Unexpected error at tests/co19/src/LanguageFeatures/Primary-constructors/static_processing_A22_t02.dart line 70, column 6, length 1: COMPILE_TIME_ERROR.FINAL_NOT_INITIALIZED_CONSTRUCTOR

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Primary-constructors/static_processing_A22_t02
```

```
class C<T>([var String v1 = "", final T? v2, var bool v3 = true]) {
  String get v1 => "";
//           ^^
// [analyzer] unspecified
// [cfe] unspecified
  T v2;
//  ^^
// [analyzer] unspecified
// [cfe] unspecified
  void v3() {}
//     ^^
// [analyzer] unspecified
// [cfe] unspecified
}
```
Same problem as in https://github.com/dart-lang/co19/issues/3542. `T v2;` is potentially non-nullable and uninitialized, causing an error to be reported.

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Primary-constructors/static_processing_A22_t02.dart [hunk 1]
```diff
@@ -70,8 +70,8 @@ extension type ET2([String v = ""]) {
 enum E<T>([final T? v1, final String v2 = "", final bool v3 = true]) {
   e0<int>(1, "E1", true);
 
-  final T v1;
-//        ^^
+  final T? v1;
```
Comment (eernstg) [inline LanguageFeatures/Primary-constructors/static_processing_A22_t02.dart]: I think this will work:
```suggestion
  final T? v1 = null;
```
