### PR TITLE
Fixes #1708. Specify type of the list pattern

### LINKED ISSUE #1708: co19/LanguageFeatures/Patterns/variable_A03_t01
```
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Patterns/variable_A03_t01
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 43ms):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=patterns,records --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Patterns/variable_A03_t01.dart

static error failures:
- Unexpected error at line 44, column 26, length 1: COMPILE_TIME_ERROR.LIST_ELEMENT_TYPE_NOT_ASSIGNABLE

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Patterns/variable_A03_t01
```

Code
```
  final [c, String d] = [1, "2"];
  c = 2;
```
Here, the inferred required type of `[c, String d]` is `String`. So, `[1, "2"]` is `List<String>`, and `1` is not a valid element.

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Patterns/variable_A03_t01.dart [hunk 1]
```diff
@@ -41,7 +41,7 @@ main() {
 //^
 // [analyzer] unspecified
 // [cfe] unspecified
-  final [c, String d] = [1, "2"];
+  final <Object>[c, String d] = [1, "2"];
```
Comment (eernstg) [inline LanguageFeatures/Patterns/variable_A03_t01.dart:44]: Wouldn't this be a compile-time error, because `String d` is a variable pattern with a built-in downcast when it occurs in a list pattern whose element type is `Object`?

**Review by eernstg — COMMENTED** [review]
A question came up.

File: LanguageFeatures/Patterns/variable_A03_t01.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Patterns/variable_A03_t01.dart]: Fixed. Please rereview

File: LanguageFeatures/Patterns/variable_A03_t01.dart [hunk 2]
```diff
@@ -41,7 +41,7 @@ main() {
 //^
 // [analyzer] unspecified
 // [cfe] unspecified
-  final [c, String d] = [1, "2"];
+  final [int c, String d] = [1, "2"];
```
Comment (eernstg) [inline LanguageFeatures/Patterns/variable_A03_t01.dart:44]: Has it actually been fixed? To me it looks like `[1, "2"]` infers as `<Object>[1, "2"]` and both `int c` and `String d` are variable patterns with a built-in downcast, and they are errors in a declaration context. Cf. [this sentence](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=Also%20variable%2C%20list%2C%20map%2C%20record%2C%20and%20object%20patterns%20only%20match%20a%20value%20of%20a%20certain%20required%20type.%20These%20patterns%20are%20prohibited%20in%20an%20irrefutable%20context%20if%20the%20matched%20value%20isn%27t%20assignable%20to%20that%20type.).

**Review by eernstg — COMMENTED** [review]
I still think we should expect a compile-time error.

File: LanguageFeatures/Patterns/variable_A03_t01.dart (hunk 2 above)
Comment (scheglov) [reply LanguageFeatures/Patterns/variable_A03_t01.dart:44]: The type schema for list pattern here is the greatest lower bound of `int` and `String`, so `Never`, e.i. we infer `final [int c, String d] = <Never>[1, "2"];`, which is an error.

**Comment by sgrekhov** [comment]
Fixed. Please review

File: LanguageFeatures/Patterns/variable_A03_t01.dart (hunk 2 above)
Comment (eernstg) [reply LanguageFeatures/Patterns/variable_A03_t01.dart]: Ah, I got the direction wrong: The pattern actually [gets an inferred type argument](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=the%20inner%20subpattern.-,List%3A,-A%20context%20type) which is then carried over to the initializing expression. But it's still an error. ;-)

So I have several comments which are wrong in the same way. Thanks for clarifying this!

**Review by eernstg — APPROVED** [review]
LGTM
