### PR TITLE
Fixes #2384. Fix not well-bound extension types. Add function-type dynamic test

### LINKED ISSUE #2384: co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t02
```console
FAILED: dart2analyzer-none release_arm64 co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t02
Expected: Pass
Actual: MissingCompileTimeError

--- Command "dart2analyzer" (took 07.000554s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --enable-experiment=inline-class --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t02.dart

static error failures:
- Unexpected error at line 22, column 18, length 1: COMPILE_TIME_ERROR.TYPE_PARAMETER_SUPERTYPE_OF_ITS_BOUND

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t02
```

@eernstg confirmed in chat that this is a valid diagnostic.

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+/// it executes the body of Dm in an environment where this and the name of the
+/// representation are bound in the same way as in the getter invocation, the
+/// type variables of V are bound to the actual values of T1, .. Ts, and the
+/// formal parameters of m are bound to args1 in the same way that they would be
+/// bound for a normal function call. If the body completes returning an object
+/// o2 then the invocation evaluates to o2. If the body throws an object and a
+/// stack trace then the invocation completes throwing the same object and stack
+/// trace.
+///
+/// @description Check invocation of an extension type `call` member
```
Comment (eernstg) [inline LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart:28]: I can't actually see any extension type members named `call`. There is a function type, `Object Function(num)`, in the bound of `T`, and there are other function types like `Foo`, but I don't see any situations where an invocation of a method named `call` takes place, and said method is a member of an extension type.

That might be hard to achieve anyway, because an extension type can't have `implements T` where `T` is a function type. So it's difficult to find a `call` method anywhere unless we use `id` to look up an actual function.

I suppose it isn't actually worthwhile to try to check the invocation of an extension type `call` method when that `call` method comes from a function type, we can only do it using a callable class or a callable extension type.

File: LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+/// extension type V<X1 extends B1, .. Xs extends Bs>(T id) ... {
+///   ... // Members.
+/// }
+/// ...
+/// A compile-time error occurs if the type V<T1, .. Tk> provides a wrong number
+/// of type arguments to V (when k is different from s), and if it is not
+/// regular-bounded.
+///
+/// @description Checks that it is a compile-time error if the type
+/// `V<T1, .. Ts>` is not well-bounded
```
Comment (eernstg) [inline LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart:17]: I don't see any situations below where there is a type of the form `V<T1, .. Ts>` which isn't well-bounded (and it's actually an error already if it isn't regular-bounded, e.g., if it's super-bounded).

The code below seems to check something different, namely situations where there is a compile-time error caused by declarations of bounds that do not satisfy the requirements (in this case: no cycles).

So maybe it's just a matter of saying that this checks for the processing of declarations with cycles in the bounds?

File: LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t01.dart [hunk 3]
```diff
@@ -26,6 +26,8 @@ void foo<X extends V<Y>, Y extends X>() {} // foo<X extends Y, Y extends X>()
 // [analyzer] unspecified
 // [cfe] unspecified
 
+
```
Comment (eernstg) [inline LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t01.dart:29]: Spurious extra empty lines?

**Review by eernstg — COMMENTED** [review]
I think there are a couple of tests whose description doesn't match the contents.

File: LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart (hunk 1 above)
Comment (sgrekhov) [reply LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart]: The description rewritten to reflect that here we are testin method `call` of a representation type. Added `dynamic_semantics_member_invocation_A03_t06.dart` which tests method `call` of an extension type. I think it makes sense to have one test checking that this functionality works for extension types as well

File: LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart (hunk 2 above)
Comment (sgrekhov) [reply LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart]: The description rewritten

File: LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t01.dart (hunk 3 above)
Comment (sgrekhov) [reply LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t01.dart]: Removed

**Review by sgrekhov — COMMENTED** [review]
Updated. Please take another look

File: LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart (hunk 1 above)
Comment (eernstg) [reply LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart]: OK, thanks!

File: LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart (hunk 2 above)
Comment (eernstg) [reply LanguageFeatures/Extension-types/static_analysis_extension_types_A05_t04.dart]: Great, this is surely a test that we should have, and now I understand what's going on! ;-)

**Review by eernstg — APPROVED** [review]
LGTM
