### PR TITLE
Fixes #2115. Fix roll failures (mixin tests)

### LINKED ISSUE #2115: Failures on [co19] Roll co19 to 37d3bc8788b45d6b8cb64add43ab2ab5cec62893
There are new test failures on [[co19] Roll co19 to 37d3bc8788b45d6b8cb64add43ab2ab5cec62893](https://dart-review.googlesource.com/c/sdk/+/312300).

The tests
```
co19/Language/Generics/scope_t05 Crash (expected Pass)
co19/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t05 Crash (expected Pass)
co19/Language/Interfaces/Combined_Member_Signature/combined_member_signature_A03_t06 Crash (expected Pass)
co19/Language/Mixins/Mixin_Classes/deferred_t01 MissingCompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Classes/deferred_t02 MissingCompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Classes/deferred_t03 MissingCompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Classes/syntax_A03_t02 MissingCompileTimeError (expected Pass)
co19/Language/Mixins/Mixin_Classes/syntax_A04_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/overriding/override_checking_A01_CLASSPARAM_t23 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/overriding/override_checking_A01_CLASSPARAM_t24 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/overriding/override_checking_A01_CLASSPARAM_t27 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/weak/overriding/override_checking_A01_CLASSPARAM_t28 CompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-linux-chrome-unsound
dart2js-hostasserts-linux-d8
dart2js-linux-chrome
dart2wasm-linux-chrome
dart2wasm-linux-d8
ddc-linux-chrome
ddc-linux-chrome-unsound
vm-mac-debug-arm64
vm-mac-release-arm64
```

### PR DESCRIPTION
**Pull request by sgrekhov**

### CODE REVIEW

File: Language/Mixins/Mixin_Classes/syntax_A04_t02.dart [hunk 1]
```diff
@@ -38,7 +38,7 @@ class C<T> extends S with M {
 
 main() {
   C c = new C();
-  c.m1.expectStaticType<Exactly<num?>>();
-  c.m2.expectStaticType<Exactly<String?>>();
-  c.s.expectStaticType<Exactly<Object?>>();
+  c.m1?.expectStaticType<Exactly<num>>();
+  c.m2?.expectStaticType<Exactly<String>>();
+  c.s?.expectStaticType<Exactly<Object>>();
```
Comment (eernstg) [inline Language/Mixins/Mixin_Classes/syntax_A04_t02.dart:43]: This is confusing: `C` means `C<dynamic>`, but that doesn't actually matter because we will get an `S<dynamic>` and an `M<num, String>` as superinterfaces no matter what (because of the raw types used as superinterfaces), and this means that `c.m1` and `c.m2` will have types `num` and `String`, but `c.s` will have the type `dynamic`.

So we can't execute an extension method on `c.s`, but when we're using `c.s?.expect...` we will avoid trying to call anything, because `c.s == null`.

So the `?` in `c.s?.` is crucial, but in `c.m1?.` and in `c.m2?.` it should be unnecessary.

I actually think it would be nicer to test this using `if (2 < 1) c.s.whatever;` as usual, and then keep the old forms in line 41 and 42.

**Review by eernstg — COMMENTED** [review]
I think it's slightly misleading to use null to avoid calling a non-existing instance member as if it were an extension method. ;-)

**Review by eernstg — APPROVED** [review]
LGTM
